6a66da923a559382d399262430d1adbb6adb7a4f: Pulling from gr0v1ty/nano-node
a8b1c5f80c2d: Already exists
dfcd4025b373: Pulling fs layer
f66963198510: Pulling fs layer
f4396c5548ec: Pulling fs layer
871e3d5e0e1d: Pulling fs layer
977a7763c6f1: Pulling fs layer
93620d08a7d5: Pulling fs layer
844a6a1218e1: Pulling fs layer
4f4fb700ef54: Pulling fs layer
b715a6073cb8: Pulling fs layer
4e23faf81b73: Pulling fs layer
871e3d5e0e1d: Waiting
977a7763c6f1: Waiting
93620d08a7d5: Waiting
844a6a1218e1: Waiting
4f4fb700ef54: Waiting
4e23faf81b73: Waiting
b715a6073cb8: Waiting
dfcd4025b373: Verifying Checksum
dfcd4025b373: Download complete
871e3d5e0e1d: Download complete
977a7763c6f1: Verifying Checksum
977a7763c6f1: Download complete
93620d08a7d5: Verifying Checksum
93620d08a7d5: Download complete
f4396c5548ec: Verifying Checksum
f4396c5548ec: Download complete
dfcd4025b373: Pull complete
844a6a1218e1: Verifying Checksum
844a6a1218e1: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
b715a6073cb8: Download complete
4e23faf81b73: Verifying Checksum
4e23faf81b73: Download complete
f66963198510: Verifying Checksum
f66963198510: Download complete
f66963198510: Pull complete
f4396c5548ec: Pull complete
871e3d5e0e1d: Pull complete
977a7763c6f1: Pull complete
93620d08a7d5: Pull complete
844a6a1218e1: Pull complete
4f4fb700ef54: Pull complete
b715a6073cb8: Pull complete
4e23faf81b73: Pull complete
Digest: sha256:1105d86ed3d81a30a2fe7399ae807feed69d05cebcba23fd155db5b840048f29
Status: Downloaded newer image for gr0v1ty/nano-node:6a66da923a559382d399262430d1adbb6adb7a4f
docker.io/gr0v1ty/nano-node:6a66da923a559382d399262430d1adbb6adb7a4f
https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_conf_send_independant.json
Start Fetching '5n4pr_conf_send_independant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_independant_config.json'
Done  Fetching '5n4pr_conf_send_independant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_independant_config.json'
Start Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Done  Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Start Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Done  Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
SUCCESS: stop_containers completed with None result.
SUCCESS: reset_nodes_data completed with None result.
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
Error executing command: nanomock start && nanomock init_wallets
Error: ERROR: Command failed: docker-compose -f /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml -p nanomock up -d
ERROR: Error output: Creating volume "nanomock_nl_default_volume" with default driver
Creating nl_pr2 ... 
Creating nl_pr4 ... 
Creating nl_pr1 ... 
Creating nl_pr3 ... 
Creating nl_genesis ... 
Creating nl_pr1     ... done
Creating nl_pr1_exporter ... 
Creating nl_pr3          ... done
Creating nl_pr3_exporter ... 
Host is already in use by another container
Creating nl_pr2          ... error

ERROR: for nl_pr2  Cannot start service nl_pr2: driver failed programming external connectivity on endpoint nl_pr2 (5435b6f8f937e1c6a2d23f371ac9677cb6d2dae00c22fe77ab45fdc000a8ab15): Error starting userland proxy: listen tcp4 0.0.0.0:44102: bind: address already in use
Creating nl_genesis      ... done
Creating nl_genesis_exporter ... 
Creating nl_pr4              ... done
Creating nl_pr4_exporter     ... 
Creating nl_pr1_exporter     ... done
Creating nl_pr3_exporter     ... done
Creating nl_genesis_exporter ... done
Creating nl_pr4_exporter     ... done

ERROR: for nl_pr2  Cannot start service nl_pr2: driver failed programming external connectivity on endpoint nl_pr2 (5435b6f8f937e1c6a2d23f371ac9677cb6d2dae00c22fe77ab45fdc000a8ab15): Error starting userland proxy: listen tcp4 0.0.0.0:44102: bind: address already in use
Encountered errors while bringing up the project.

ERROR: Return code: 1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 198, in subprocess_run_capture_output
    result = subprocess.run(cmd,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker-compose -f /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml -p nanomock up -d' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/nanomock", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 58, in main
    asyncio.run(main_async(args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 54, in main_async
    await manager.execute_command(args.command, args.nodes, args.payload)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 506, in execute_command
    await command_func(**filtered_command_args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 57, in async_wrapper
    result = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 435, in start_containers
    self.docker_interface.compose_start(nodes)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/docker/mixin.py", line 56, in compose_start
    return self._run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/docker/mixin.py", line 33, in _run_command
    subprocess_run_capture_output(base_command)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 209, in subprocess_run_capture_output
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: <exception str() failed>
.DEBUG 2 unconfirmed blocks! e.g. 92A7F5D3A1B8EBD0C67F182C0744FA43D91EFB0818AB7CDC486FD7C54157D91E
.DEBUG 2 unconfirmed blocks! e.g. 86F64D90236703517372CB4F371ACBED42BA169370E61B0EAB14F71BF99D4C64
.DEBUG 2 unconfirmed blocks! e.g. B64378A4A7D8F0075215473654EE802015F72C404A49CB44D86F17591C3D158A
.DEBUG 2 unconfirmed blocks! e.g. 12462E4B5EF04A5AEB0522252A27B6757969F199FFA55DDEF4921E34AEAEF0C6
.DEBUG 2 unconfirmed blocks! e.g. E5C492B0ED71737B680E2B70D6DF0EAEAB330D7E091B9A5C8544948906F69427
.DEBUG 2 unconfirmed blocks! e.g. A886E4453A187BC407022188A245A72D6D880E1F7022444EC2225909FF0F4510
.DEBUG 2 unconfirmed blocks! e.g. 5BF7BC02E69E32D83A53A3515FF856F7BD60E2B343043E4D276ABA98DFB42D46
.DEBUG 2 unconfirmed blocks! e.g. E4CF8D2FD3CBA56FC82028D988AD1AB84E2A51E1D6D2AD746CCD56F7FFA118FF
.DEBUG 2 unconfirmed blocks! e.g. 5F163569074A3A05078A1F9D51B738677DCED1048570DF4213FDFD771A7BAC3D
.DEBUG 2 unconfirmed blocks! e.g. 5FA9252191C56734ED5E9CE6D1906D315A2AB7848EF5561855F31BAE661D0D38
.DEBUG 2 unconfirmed blocks! e.g. 19C2EB2776BECCA8869C920CB1034F49D6C05B1F253F7283F6B169C86030C0FF
.DEBUG 2 unconfirmed blocks! e.g. BB061FA2B71149320829F5923FB1EB581397B5C4A08D97EB605E3F8C7B99B1C4
.DEBUG 2 unconfirmed blocks! e.g. B30FEE54AFE573C2DFC21D30517A7BDC0EF8668B06EB13A71218B599C3CFB506
.DEBUG 2 unconfirmed blocks! e.g. 8DCFEBE3FF1FE9018771BA5AE861E92ACCFDA5DA6925995B759E25AD1C9D5777
.DEBUG 2 unconfirmed blocks! e.g. D9622AE8B34D6044029F778DDE8708862B76443E6A03795D7665D97A3678AC8C
.DEBUG 2 unconfirmed blocks! e.g. DD28B8A6717A19171F99E629140ABDCF1527DA2EEF5510B9EEFFB3DD3CCF3815
.DEBUG 2 unconfirmed blocks! e.g. 5AD6BC2E73C6812A3DE0D0B2AFF0D896446D351B28FF5DBD013FB50C6093C25C
.DEBUG 2 unconfirmed blocks! e.g. 99B380E39D35210CE0C49727EF5BA5450FEF54C49B98BF6910D9669E782BE1B4
.DEBUG 2 unconfirmed blocks! e.g. 6CA1C4F6214FF82E3ECB3A79BEF70310F72B7B16D82F0083CAB6527EF0D039B8
.DEBUG 2 unconfirmed blocks! e.g. 65443053FA7E36926A6FA40862ED8287745072EF41965E91FFB770A4BF20F5EC
.DEBUG 2 unconfirmed blocks! e.g. CEB6E24F00ECFF20BF9143849A82B2ECC6F69821AE0B933EE7136F7769D04B76
.DEBUG 2 unconfirmed blocks! e.g. CF7615378F7EAC2F37BFDDC6C2CB0BDA1B282811F67437C273F62C82EC72C12C
.DEBUG 2 unconfirmed blocks! e.g. 6D922254260023D520A91CA4E7BCFF69CF4AC70B599A2039868DF4E51B60861F
.DEBUG 2 unconfirmed blocks! e.g. 3501418AEA48E9BA50597AD7351D2F274E6D4ABCF38443C378A234D744161BBE
.DEBUG 2 unconfirmed blocks! e.g. 4ACFCEDE07A338B3995ADF040BF5636521104548715D0C4DC847FE8CC96692EF
.DEBUG 2 unconfirmed blocks! e.g. 01B6C97B1746AB57253EB71C2A24914A61120F2A699B200097DD9543A64F1919
.DEBUG 2 unconfirmed blocks! e.g. BD236D7CDF6E236BED4C20F8DFDC71F48017B3AF7E9AA29A1220B2CB82E77628
.DEBUG 2 unconfirmed blocks! e.g. CA4B9EF19F9E7B8E0CA83A9ACA8C2204FCBBA510A8B7888B8B3219733258B2CF
.DEBUG 2 unconfirmed blocks! e.g. 4E5C5B8AC4A19E07997404C4B92F583A9D1120AE9BB61A54B883148603830943
.DEBUG 2 unconfirmed blocks! e.g. DFD3B8C311BB1E691603A923A53A7EECC2CA8A03A07ADA5C300C9758A903B306
.DEBUG 2 unconfirmed blocks! e.g. 0611875491785921A73C1EB663CF38D5F458D3BFDB094986F239ABB0F20CA092
.DEBUG 2 unconfirmed blocks! e.g. 63E9D710FE5982B94D3A34499E05661586B34D762BA5C5676DCCBA28E73DA545
.DEBUG 2 unconfirmed blocks! e.g. E2D857B099BACCCD66A286F00171F4C641CA410F4A925116FE25AFF527EB0E8D
.DEBUG 2 unconfirmed blocks! e.g. 6C753242FE43853F3DEFF1D039AE8EF6CCA613DEEED77038BF352E983A12A2A0
.DEBUG 2 unconfirmed blocks! e.g. CEC357616876228FF87C0083EA98B591923956ED2A730177DD3DC0EE69EB207C
.DEBUG 2 unconfirmed blocks! e.g. 04603FCF3E6F6B0E4AA9D6104F3F591B31A0B1F0D0D75F3ADC6A54B9E6F7C74F
.DEBUG 2 unconfirmed blocks! e.g. 3DE54288D7681C73581845DF337E5B19B13AF500642E210BEAE3024108227819
.DEBUG 2 unconfirmed blocks! e.g. 09C2BDC3FC820B9EF70EE800F2A2B6311D69A5072F917FCCE15D5BBEE7576822
.DEBUG 2 unconfirmed blocks! e.g. D4A895A1F6E4047C96B7E4F2BE75384FC106FE55442892E59EC355A86FD2A5FB
.DEBUG 2 unconfirmed blocks! e.g. 41872BF3E2879C811F5C5BAF6FA62DCEA6D1E867445D1CDE68AB77580C529489
.DEBUG 2 unconfirmed blocks! e.g. 6ACE1688E97A5B1361C79E645D9FE5C1484BFD6A60BF7E2E6DBD728293FEE9EF
.DEBUG 2 unconfirmed blocks! e.g. F117D023E67BB5E47B8E95F8308154B3C49490B40214D2D01F63BEC750B455D0
.DEBUG 2 unconfirmed blocks! e.g. AF9CC519635A690ABD1EB7D14E30BEB6AAE8974C4FB5104B2EA461601C7B63FE
.DEBUG 2 unconfirmed blocks! e.g. 56F26E156BD531763BA0FE43B0A6841EEDBF7E1D02B38F9E23EA7B5BAC81DD9B
.DEBUG 2 unconfirmed blocks! e.g. 7EB8E13F7DA7550075089EEDE89824822E75B1F16CB6784BF194904EE5550F30
.DEBUG 2 unconfirmed blocks! e.g. DF3F971D49AA82408DB24C673D4F2FA1EAA6CFD88166D51421F022C6552FD5FD
.DEBUG 2 unconfirmed blocks! e.g. 1B04E77A0B5003918DB3B651C5DA0816B46A48385E8F6CE9A521E6551D130BC5
.DEBUG 2 unconfirmed blocks! e.g. A774B2003A789D05511BCD02F6CBF7BF86922730887DAA1209E80BB0F153E8EF
.DEBUG 2 unconfirmed blocks! e.g. EC02496660E43CC6EFB26853C797C363EA919974000CD439259B31F9DD9C36C9
.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/threaded_command_mixin.py", line 26, in _execute_command_sequence
    self.command_instance.execute_another_command(command_config)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 35, in publish_create
    asyncio.run(test_case.run())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 115, in run
    await self.stats_manager.initialize(self.node_name)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/confirmation_stats.py", line 17, in initialize
    start_block_count = await self.nanorpc.block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 50, in block_count
    return await self.rpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 95, in _retry_on_exception
    raise MaxRetriesExceededError(
nanorpc.client_dynamic.MaxRetriesExceededError: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
DEBUG 2 unconfirmed blocks! e.g. 63B84609C679B5C99D960AB9A5BDA447AEB606AF651ED5A814D3EC0A22F1DEB1


00:52:04 confs    | timeouts | bps      | cps      | min_conf_s | max_conf_s | perc_50_s | perc_75_s | perc_90_s | perc_99_s | block_timeout_s | total_s  | new_blocks | new_cemented |
00:52:04 0        | 100      | 0.4      | 0.0      | -1         | -1         | -1        | -1        | -1        | -1        | 5               | 252.51   | 100        | 0            |
